from django.conf.urls import url
from . import views, auth_views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search$', views.search, name='search'),
    url(r'^menu/([a-z]*)$', views.menu, name='menu'),
    url(r'^create$', views.create, name='create'),
    url(r'^post/([1-9][0-9]*)$', views.post, name='post'),
    url(r'^post/([1-9][0-9]*)/reply$', views.reply, name='reply'),
    url(r'^shop_info/([1-9][0-9]*)$', views.shop_info, name='shop_info'),
    url(r'^post/([1-9][0-9]*)/purchase$', views.purchase, name='purchase'),
    url(r'^shoppingcart$', views.shoppingcart, name='shoppingcart'),
    url(r'^create_complete$', views.create_complete, name='create_complete'),
    url(r'^post/([1-9][0-9]*)/delete$', views.post_delete, name='post_delete'),
    url(r'^post/([1-9][0-9]*)/modify$', views.post_change, name='post_change'),
    url(r'^mycart$', views.my_cart, name='mycart'),
    url(r'^add_item/([1-9][0-9]*)/shoppingcart$', views.shoppingcart, name='shoppingcart'),
    url(r'^user([1-9][0-9]*)/order', views.my_order, name='my_order'),
    url(r'^purchase_success$', views.purchase_success, name='purchase_success'),
    url(r'^search/([^-~]*)/([0-9]*)/([^-~]*)/([a-z]*)$', views.filter, name='filter'),
    url(r'^send_clicked/([1-9][0-9]*)/$', views.send_clicked, name='send_clicked'),
    url(r'^receive_clicked/([1-9][0-9]*)/$', views.receive_clicked, name='receive_clicked'),
    url(r'^needcharge$',views.purchase_fail,name='purchase_fail'),
    url(r'^mycart/delete$', views.mycart_delete, name='mycart_delete'),
    url(r'^mycart/purchase$', views.mycart_purchase, name='mycart_purchase'),

    # auth
    url(r'^login$', auth_views.login, name='login'),
    url(r'^authenticate$', auth_views.authenticate, name='authenticate'),
    url(r'^signup$', auth_views.signup, name='signup'),
    url(r'^signup/submit$', auth_views.signup_submit, name='signup-submit'),
    url(r'^open$', auth_views.open, name='open'),
    url(r'^open/submit$', auth_views.open_submit, name='open-submit'),
    url(r'^logout$', auth_views.logout, name='logout'),
    url(r'^modify$', auth_views.modify, name='modify'),
    url(r'^changepwd$', auth_views.changepwd, name='changepwd'),
    url(r'^modify/seller/([1-9][0-9]*)$', auth_views.modify_seller, name='modify-seller'),
    url(r'^modify/buyer/([1-9][0-9]*)$', auth_views.modify_buyer, name='modify-buyer'),
    url(r'^changepwd/pwd/([1-9][0-9]*)$', auth_views.change_pwd, name='changepwd-pwd'),
    url(r'^recharge$', auth_views.recharge, name='recharge'),
    url(r'^recharge/recharge_complete/([1-9][0-9]*)$', auth_views.recharge_complete, name='recharge_complete'),
    url(r'^withdraw$', auth_views.withdraw, name='withdraw'),
    url(r'^withdraw/withdraw_complete/([1-9][0-9]*)$', auth_views.withdraw_complete, name='withdraw_complete'),
]
